sudo: required

services:
    - docker

    before_install:
     - docker build  -t satzmani/docker-react -f Dockerfile.dev .  


     script:
        - docker run satzmani/docker-react npm run test -- --coverage

    